repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v4.0.0-alpha.8' # Use the sha / tag you want to point at
      hooks:
          - id: prettier
            types_or: [css, javascript, ts, scss, json, html]

    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
            args: [-l 120]

    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: 'v0.0.262'
      hooks:
          -   id: ruff
